#!/usr/bin/env tsx
/**
 * Generator for `lib/farm-schema.ts` — the canonical bootstrap DDL applied to
 * every freshly provisioned tenant database.
 *
 * Why this exists
 * ---------------
 * `lib/farm-schema.ts` is the schema NEW tenants get at provision time (via
 * `lib/seed-farm-db.ts`). It MUST equal what `prisma/schema.prisma` declares —
 * otherwise a new farm is born missing tables/columns the app code expects and
 * 500s on its first action (the #280 / H0b onboarding-drift incident class).
 *
 * The file was previously regenerated by a *manual* copy-paste of
 * `prisma migrate diff` output. That step was skipped after a schema change and
 * the bootstrap silently rotted (29 tables committed vs 43 declared). This
 * script removes the manual step:
 *
 *   pnpm db:gen-schema         — regenerate lib/farm-schema.ts in place
 *   pnpm db:gen-schema:check   — exit 1 if the committed file is stale (CI gate)
 *
 * It emits two exports:
 *   - FARM_SCHEMA_SQL          — the full from-empty DDL (source of truth:
 *                                prisma/schema.prisma).
 *   - BASELINE_MIGRATION_NAMES — every migrations/NNNN_*.sql filename. The DDL
 *                                above already reflects all of their effects, so
 *                                a freshly provisioned tenant must have these
 *                                stamped as applied in `_migrations` (see
 *                                lib/seed-farm-db.ts) or a later `pnpm db:migrate`
 *                                would try to re-apply them and fail on an
 *                                already-existing column/table.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

const REPO_ROOT = fileURLToPath(new URL('..', import.meta.url));
const TARGET = join(REPO_ROOT, 'lib', 'farm-schema.ts');
const PRISMA_BIN = join(REPO_ROOT, 'node_modules', '.bin', 'prisma');
const MIGRATIONS_DIR = join(REPO_ROOT, 'migrations');

/** Run `prisma migrate diff` and return the from-empty DDL for the schema. */
function generateSchemaSql(): string {
  const out = execFileSync(
    PRISMA_BIN,
    [
      'migrate',
      'diff',
      '--from-empty',
      '--to-schema-datamodel',
      'prisma/schema.prisma',
      '--script',
    ],
    { cwd: REPO_ROOT, encoding: 'utf-8', maxBuffer: 16 * 1024 * 1024 },
  );
  return out.replace(/\s+$/, '');
}

/** Leaf `migrations/NNNN_*.sql` filenames, sorted — same shape loadMigrations uses. */
function listMigrationNames(): string[] {
  return readdirSync(MIGRATIONS_DIR)
    .filter((f) => f.endsWith('.sql'))
    .sort((a, b) => a.localeCompare(b));
}

/** Escape a string for safe embedding inside a JS template literal. */
function escapeForTemplateLiteral(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

function renderFile(schemaSql: string, migrationNames: readonly string[]): string {
  const names = migrationNames.map((n) => `  '${n}',`).join('\n');
  return `/**
 * SQL schema for new per-farm databases.
 *
 * AUTO-GENERATED — DO NOT EDIT BY HAND.
 * Regenerate after any prisma/schema.prisma change with:
 *   pnpm db:gen-schema
 * CI fails if this file is stale: pnpm db:gen-schema:check
 *
 * Source of truth: prisma/schema.prisma, via
 *   prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --script
 */
export const FARM_SCHEMA_SQL = \`
${escapeForTemplateLiteral(schemaSql)}
\`;

/**
 * Every numbered migration under migrations/ as of generation time. The schema
 * above already reflects all of their effects, so a freshly provisioned tenant
 * must have these stamped as applied in \`_migrations\` (see lib/seed-farm-db.ts):
 * otherwise \`pnpm db:migrate\` would try to re-apply them and fail on an
 * already-existing column or table.
 */
export const BASELINE_MIGRATION_NAMES: readonly string[] = [
${names}
];
`;
}

function main(): void {
  const check = process.argv.includes('--check');
  const generated = renderFile(generateSchemaSql(), listMigrationNames());

  if (check) {
    const current = readFileSync(TARGET, 'utf-8');
    if (current !== generated) {
      console.error(
        'lib/farm-schema.ts is STALE relative to prisma/schema.prisma.\n' +
          'Run `pnpm db:gen-schema` and commit the result.\n' +
          '(A new tenant provisioned from a stale bootstrap is born missing\n' +
          ' tables/columns the app expects — the onboarding-500 / #280 class.)',
      );
      process.exit(1);
    }
    console.log('lib/farm-schema.ts is up to date.');
    return;
  }

  writeFileSync(TARGET, generated);
  console.log(
    `Wrote lib/farm-schema.ts (${generated.match(/CREATE TABLE/g)?.length ?? 0} tables, ` +
      `${listMigrationNames().length} baseline migrations).`,
  );
}

main();
